### ISSUE TITLE
UIWebViewの使用について

### ISSUE THREAD

**Issue by fromkk** [SIROK/growthbeat-ios#102]
Appleより新規アプリの場合は2020年4月まで、アップデートの場合2020年12月までアプリを受け付けるとの発表がありました。
内部的に `UIWebView` を利用している様なので `WKWebView` の利用に差し替えをお願いしたいです。

参考: https://developer.apple.com/news/?id=12232019b

**Comment by yasumatsunoboru** [comment]
@fromkk ご指摘ありがとうございます。
GrowthLinkサービスの提供終了に伴い、 `UIWebview` の利用箇所を削除した
iOS SDK v2.0.7 をリリースしております。よろしければご利用ください。

Growthbeatお客様向けブログ
https://sirok-growthbeat.amebaownd.com/posts/7722541

**Comment by fromkk** [comment]
ありがとうございます！
