### ISSUE TITLE
The client will be not initialized when occurring a network error or server error on the first launching

### ISSUE THREAD

**Issue by subway123** [SIROK/growthbeat-ios#46]
https://github.com/growthbeat/growthbeat-ios/blob/master/source/Growthbeat/GrowthbeatCore/GrowthbeatCore.m#L139-L148

アプリ初回起動時にネットワークエラーやサーバーエラーが発生した場合、
clientが初期化できずに上記のwaitClientで無限ループします。

**Comment by ohageeq** [comment]
先ほどリリースしました、1.2.6のバージョンで対応いたしました。

**Comment by subway123** [comment]
@mugi65 
確認しました。ご対応ありがとうございました。
