### ISSUE TITLE
Lots of warning when generating dSYM

### ISSUE THREAD

**Issue by rb-de0** [SIROK/growthbeat-ios#48]
バージョン 1.2.6
Xcode 7.2
SDK 9.2

CocoaPodsで本ライブラリを導入しています。
ビルド中「Generate dSYM」の段階で非常に多くのwarningが表示されます。

こちら
https://forums.developer.apple.com/thread/17921

と同じ現象だと思われますが、GCC_PRECOMPILE_PREFIX_HEADERやCLANG_ENABLE_MODULESのフラグを設定してもwarningが解消されません。

こちらライブラリ側で対応可能でしょうか。

**Comment by rb-de0** [comment]
追記です。

こちら作成者側のキャッシュが関係しているかもしれません。
参考：http://qiita.com/toguri/items/a0a05d2da67801470ecd

**Comment by yshrkt** [comment]
I got same issue, too.

**Comment by sotayamashita** [comment]
@rb-de0 共有していただきありがとうございます。ログを gist などに貼ってリンクを頂くことができますか？ 

こちら側でこのようなログが出ていないのですがこの警告がでることで正しく SDK を導入することができませんか？

**Comment by sotayamashita** [comment]
@yshrkt Oops, we are trying to identify the cause.

**Comment by yshrkt** [comment]
I try to use growthbeat in swift project, and set up using cocoapods.
You will be able to get a lot of warnings if you set `Build Settings > Build Options > Debug Information Format` to `DWARF with dSYM File` in swift project.

My Environment:
Xcode 7.2.1
iOS SDK 9.2

**Comment by sotayamashita** [comment]
@yshrkt I appreciate your quick reply. I will reproduce on my environment. https://github.com/growthbeat/Growthbeat-SDK-iOS-Starter-Project. 

Is this problem ?

**Comment by yshrkt** [comment]
@sotayamashita Thank you for sample project.

I got a log of warnings like as belows:

```
GenerateDSYMFile /Users/test/Library/Developer/Xcode/DerivedData/GrowthbeatStarterProject-Swift-gmvuyxkiefyugxaxyomhcnlkbthg/Build/Products/Release-iphoneos/GrowthbeatStarterProject-Swift.app.dSYM /Users/test/Library/Developer/Xcode/DerivedData/GrowthbeatStarterProject-Swift-gmvuyxkiefyugxaxyomhcnlkbthg/Build/Products/Release-iphoneos/GrowthbeatStarterProject-Swift.app/GrowthbeatStarterProject-Swift
    cd /Growthbeat-SDK-iOS-Starter-Project-master/ios/GrowthbeatStarterProject-Swift
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/test/Library/Developer/Xcode/DerivedData/GrowthbeatStarterProject-Swift-gmvuyxkiefyugxaxyomhcnlkbthg/Build/Products/Release-iphoneos/GrowthbeatStarterProject-Swift.app/GrowthbeatStarterProject-Swift -o /Users/test/Library/Developer/Xcode/DerivedData/GrowthbeatStarterProject-Swift-gmvuyxkiefyugxaxyomhcnlkbthg/Build/Products/Release-iphoneos/GrowthbeatStarterProject-Swift.app.dSYM

while processing /Growthbeat-SDK-iOS-Starter-Project-master/ios/GrowthbeatStarterProject-Swift/Pods/Growthbeat/Growthbeat.framework/Growthbeat(GBClient.o):
warning: /Users/a13048/Library/Developer/Xcode/DerivedData/ModuleCache/32HMNXKJ77OBW/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
while processing /Growthbeat-SDK-iOS-Starter-Project-master/ios/GrowthbeatStarterProject-Swift/Pods/Growthbeat/Growthbeat.framework/Growthbeat(GBClient.o):
warning: /Users/a13048/Library/Developer/Xcode/DerivedData/ModuleCache/32HMNXKJ77OBW/Foundation-A3SOD99KJ0S9.pcm: No object file for requested architecture
while processing /Growthbeat-SDK-iOS-Starter-Project-master/ios/GrowthbeatStarterProject-Swift/Pods/Growthbeat/Growthbeat.framework/Growthbeat(GBClient.o):
warning: /Users/a13048/Library/Developer/Xcode/DerivedData/ModuleCache/32HMNXKJ77OBW/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
...
```

[All of Warnings](https://github.com/growthbeat/growthbeat-ios/files/168512/growthbeat_warnings.txt)

**Comment by sotayamashita** [comment]
@yshrkt Please try a way below:
1. Targets -> [your project] -> Build Settings
2. Find and expand "Debug Information Format"
3. Change "Debug" value to "DWARF"
4. I left "Release" value unchanged as "DWARF with dSYM File"

**Comment by sotayamashita** [comment]
@yshrkt 

I created a new project in Xcode 6 and a new project in Xcode 7. It looks like the "Debug Information Format" default has been changed.

Xcode 6:

``` swift
DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";  
```

Xcode 7:

``` swift
DEBUG_INFORMATION_FORMAT = "dwarf";  
```

This is found in "Build Settings" -> "Build Options" -> "Debug Information Format" as mentioned above. Just wanted to give some more insight into this.

**Comment by yshrkt** [comment]
I have understood it, And I want to build it which sets `Debug Information Format` as `DWARF with dSYM File`. 
The dSYM Files are needed in order to symbolicate the crash log. So I want to generate dSYM file.
Maybe, You should set `Enabled Modules (C and Objective-C) (CLANG_ENABLE_MODULES) = NO` and rebuild your library.

**Comment by rb-de0** [comment]
@sotayamashita 

@yshrkt さんの貼ってくださったログと全く同じログが出力されます。
SDK自体の動作としては問題ないですが、デバッグシンボルの生成が正しくできているか気になっています。現在開発中のアプリにて、クラッシュの解析にdwarfではなくdSYMファイルが必須となっています。

参考：http://qiita.com/toguri/items/a0a05d2da67801470ecd

↑ こちらのリンクに書いてある通りだと思います。

https://github.com/growthbeat/growthbeat-ios/commit/cc9e1ba59298e6feedebee2eef2070089f3b360a

こちらのコミットで修正されている気がしますが。

**Comment by sotayamashita** [comment]
@rb-de0 

この部分だけコミットをマージを行います。

We are going to create PR to avoid a lot of warning.

**Comment by yshrkt** [comment]
@sotayamashita 

When will you release fixed version?
I want to know your plan.

**Comment by sotayamashita** [comment]
@yshrkt 

Here is a RC version https://github.com/growthbeat/growthbeat-ios/tree/release/1.2.7-rc and It is beta version. 1.2.7 will be release in next month.

**Comment by yshrkt** [comment]
OK, Thank you for replying.
