### ISSUE TITLE
特定の条件下でバックグランドタスク用のリソースが枯渇します

### ISSUE THREAD

**Issue by gitusp** [SIROK/growthbeat-ios#81]
1.2.7で発生しています。
2.x系でも発生しそうな箇所に思います。

---

特定の条件下でバックグラウンドタスク用のリソースが枯渇し、アプリ全体として非同期処理がままならなくなります。
原因は以下のプロパティ
https://github.com/growthbeat/growthbeat-ios/blob/527a9309153962155bcb98ce9bef5bcb4463e119/source/Growthbeat/GrowthPush/GrowthPush.m#L38
がnilの状態で、繰り返しsetTagメソッド
https://github.com/growthbeat/growthbeat-ios/blob/527a9309153962155bcb98ce9bef5bcb4463e119/source/Growthbeat/GrowthPush/GrowthPush.m#L239
を呼ぶと、それぞれのキューがwaitClientメソッド
https://github.com/growthbeat/growthbeat-ios/blob/527a9309153962155bcb98ce9bef5bcb4463e119/source/Growthbeat/GrowthPush/GrowthPush.m#L254
の箇所で処理が止まってしまい、結果全体として未消化のキューが蓄積することかと思います。

---

詳しく条件を特定できていないのですが、手元の環境だと例えばエミュレータで起動した場合は、clientが生成されませんでした。
（デバイストークンの登録ができないことと関連しているかもしれません）
（実機でも通信状況など何らかの状況で発生するかもしれません）

---

waitClientメソッド内のwhile(true)で、プロパティを監視している部分をKVOを利用するように書き換えれば、仮にclientが生成されなくても致命的な状態にはならないのではないかと思うのですが、いかがでしょうか？
以下に部分的な対応を行った差分を提示します。
https://github.com/gitusp/growthbeat-ios/pull/1/files

**Comment by ohageeq** [comment]
バックグランドタスクの改善をしました。
https://github.com/growthbeat/growthbeat-ios/releases/tag/2.0.5
